// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*goatUnlockMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (g GoatUnlock) MarshalJSON() ([]byte, error) {
	type GoatUnlock struct {
		Id        hexutil.Uint64 `json:"id"`
		Validator common.Address `json:"validator"`
		Token     common.Address `json:"token"`
		Recipient common.Address `json:"recipient"`
		Amount    *hexutil.Big   `json:"amount"`
	}
	var enc GoatUnlock
	enc.Id = hexutil.Uint64(g.Id)
	enc.Validator = g.Validator
	enc.Token = g.Token
	enc.Recipient = g.Recipient
	enc.Amount = (*hexutil.Big)(g.Amount)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (g *GoatUnlock) UnmarshalJSON(input []byte) error {
	type GoatUnlock struct {
		Id        *hexutil.Uint64 `json:"id"`
		Validator *common.Address `json:"validator"`
		Token     *common.Address `json:"token"`
		Recipient *common.Address `json:"recipient"`
		Amount    *hexutil.Big    `json:"amount"`
	}
	var dec GoatUnlock
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Id != nil {
		g.Id = uint64(*dec.Id)
	}
	if dec.Validator != nil {
		g.Validator = *dec.Validator
	}
	if dec.Token != nil {
		g.Token = *dec.Token
	}
	if dec.Recipient != nil {
		g.Recipient = *dec.Recipient
	}
	if dec.Amount != nil {
		g.Amount = (*big.Int)(dec.Amount)
	}
	return nil
}
