// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*bridgeWithdrawMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (b BridgeWithdrawal) MarshalJSON() ([]byte, error) {
	type BridgeWithdrawal struct {
		Id         hexutil.Uint64 `json:"id"`
		Amount     hexutil.Uint64 `json:"amount_in_satoshi"`
		MaxTxPrice hexutil.Uint64 `json:"max_tx_price"`
		Address    string         `json:"address"`
	}
	var enc BridgeWithdrawal
	enc.Id = hexutil.Uint64(b.Id)
	enc.Amount = hexutil.Uint64(b.Amount)
	enc.MaxTxPrice = hexutil.Uint64(b.MaxTxPrice)
	enc.Address = b.Address
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (b *BridgeWithdrawal) UnmarshalJSON(input []byte) error {
	type BridgeWithdrawal struct {
		Id         *hexutil.Uint64 `json:"id"`
		Amount     *hexutil.Uint64 `json:"amount_in_satoshi"`
		MaxTxPrice *hexutil.Uint64 `json:"max_tx_price"`
		Address    *string         `json:"address"`
	}
	var dec BridgeWithdrawal
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Id != nil {
		b.Id = uint64(*dec.Id)
	}
	if dec.Amount != nil {
		b.Amount = uint64(*dec.Amount)
	}
	if dec.MaxTxPrice != nil {
		b.MaxTxPrice = uint64(*dec.MaxTxPrice)
	}
	if dec.Address != nil {
		b.Address = *dec.Address
	}
	return nil
}
