// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*cancel1Marshaling)(nil)

// MarshalJSON marshals as JSON.
func (c Cancel1) MarshalJSON() ([]byte, error) {
	type Cancel1 struct {
		Id hexutil.Uint64 `json:"id"`
	}
	var enc Cancel1
	enc.Id = hexutil.Uint64(c.Id)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (c *Cancel1) UnmarshalJSON(input []byte) error {
	type Cancel1 struct {
		Id *hexutil.Uint64 `json:"id"`
	}
	var dec Cancel1
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Id != nil {
		c.Id = uint64(*dec.Id)
	}
	return nil
}
