// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*createValidatorMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (c CreateValidator) MarshalJSON() ([]byte, error) {
	type CreateValidator struct {
		Pubkey hexutil.Bytes `json:"pubkey"`
	}
	var enc CreateValidator
	enc.Pubkey = c.Pubkey
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (c *CreateValidator) UnmarshalJSON(input []byte) error {
	type CreateValidator struct {
		Pubkey *hexutil.Bytes `json:"pubkey"`
	}
	var dec CreateValidator
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Pubkey != nil {
		c.Pubkey = *dec.Pubkey
	}
	return nil
}
