// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*validatorLockMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (v ValidatorLock) MarshalJSON() ([]byte, error) {
	type ValidatorLock struct {
		Validator common.Address `json:"validator"`
		Token     common.Address `json:"token"`
		Amount    *hexutil.Big   `json:"amount"`
	}
	var enc ValidatorLock
	enc.Validator = v.Validator
	enc.Token = v.Token
	enc.Amount = (*hexutil.Big)(v.Amount)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (v *ValidatorLock) UnmarshalJSON(input []byte) error {
	type ValidatorLock struct {
		Validator *common.Address `json:"validator"`
		Token     *common.Address `json:"token"`
		Amount    *hexutil.Big    `json:"amount"`
	}
	var dec ValidatorLock
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Validator != nil {
		v.Validator = *dec.Validator
	}
	if dec.Token != nil {
		v.Token = *dec.Token
	}
	if dec.Amount != nil {
		v.Amount = (*big.Int)(dec.Amount)
	}
	return nil
}
